version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coffer
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
